# Generated by Django 2.0.5 on 2018-06-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uri',
            field=models.CharField(default='', max_length=255, verbose_name='uri'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='mediatype',
            field=models.CharField(max_length=255, verbose_name='Media Type'),
        ),
    ]
