# Generated by Django 2.0.5 on 2018-06-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180601_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='filename',
            field=models.CharField(default='', max_length=255, verbose_name='Filename'),
            preserve_default=False,
        ),
    ]
