# Generated by Django 2.0.5 on 2018-06-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='path',
        ),
    ]
