# Generated by Django 2.0.5 on 2018-06-19 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20180610_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, size=None),
        ),
    ]
